find_trending_companies:
  description: >
    Find the top trending Indian companies listed on NSE/BSE in the {sector} sector by searching
    the latest Indian financial news. Focus on companies from sources like:
    - Economic Times
    - Business Standard
    - Mint/LiveMint
    - MoneyControl
    - Business Today

    Search for companies with market cap above ₹1000 crores that are trending due to:
    - Quarterly earning announcement
    - New product launches or business expansions
    - Regulatory approval or government contracts
    - Strategic partnerships or acquisitions
    - Management changes or corporate actions

    Find new companies that you're not found before. Include accurate NSE/BSE ticker symbols
    (e.g., RELIANCE for Reliance Industries, TCS for Tata Consultancy Services).
  expected_output: >
    A list of 2-3 trending Indian companies in {sector} with their correct NSE/BSE ticker symbols,
    primary exchange (NSE/BSE), market capitalization in ₹ crores, and specific reason for trending
    with news source attribution.
  agent: trending_company_finder
  output_file: output/trending_companies.json

research_trending_companies:
  description: >
    Given a list of trending Indian companies, provide comprehensive analysis of each company
    by researching online. Focus on Indian market context and include:

    Financial Analysis:
    - Latest quarterly and annual financial results in INR
    - Key financial ratios (P/E, P/B, ROE, Debt-to-Equity)
    - Revenue and profit growth trends over last 3 years
    - Comparison with industry peers and Nifty 50 performance

    Corporate Governance & Ownership:
    - Promoter holding percentage and any recent changes
    - FII/DII holding patterns
    - SEBI compliance record and corporate governance rating
    - Management quality and track record

    Market Position & Competition:
    - Market share in Indian industry
    - Competitive advantages and moats
    - Key competitors and market positioning
    - Growth drivers specific to Indian market

    Investment Considerations:
    - Liquidity on NSE/BSE (average daily volume)
    - Volatility and beta relative to Nifty
    - Divided history and yield
    - Future growth prospects in Indian economy
    - Regulatory risks and policy impacts
  expected_output: >
    A comprehensive research report on each Indian company including financial performance in INR,
    promoter holdings, market position in India, SEBI compliance status, competitive analysis,
    and investment potential with specific focus on Indian market factors.
  agent: financial_researcher
  context: 
    - find_trending_companies
  output_file: output/research_report.json

pick_best_company:
  description: >
    Analyze the research findings and pick the best Indian company for investment considering
    Indian market-specific factors:

    Selection Criteria:
    - Strong financial fundamentals with consistent INR-based growth
    - Good corporate governance and stable promoter holdings
    - Leadership position in growing Indian market segment
    - Reasonable valuation compared to Indian market multiples
    - Adequate liquidity on NSE/BSE for easy entry/exit
    - Positive regulatory environment and policy tailwinds
    - Strong management with proven track record in India

    Risk Assessment:
    - Currency risks for export-oriented companies
    - Regulatory changes and government policy impacts
    - Competition from domestic and international players
    - Sectoral cyclicality and economic sensitivity
    - Corporate governance and promoter-related risks

    First, send a push notification to the user with your investment decision and a concise
    1-sentence rationale focusing on the key Indian market advantage.

    Then provide a detailed report explaining:
    - Why you chose this specific Indian company
    - Key investment highlights and competitive advantages
    - Target price and investment horizon recommendations
    - Risk factors and mitigation strategies
    - Why other researched companies were not selected
  expected_output: >
    The chosen Indian company with NSE/BSE ticker symbol and detailed investment rationale
    considering Indian market dynamics, regulatory environment, and growth prospects.
    Include specific reasons why other companies were rejected and comprehensive risk assessment
    for the Indian equity market context.
  agent: stock_picker
  context:
    - research_trending_companies
  output_file: output/decision.md